# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8918729385423db77088eccc69cb37aef1421fa66b288246bddf1949b65635d35d250bf36f661dda65b913c8c44e52107c101b2dd28d4785fb5c14aec934cc64

test:
  secret_key_base: 672cfa783398b41a1b64562a4aaee0b4d578ca48dddf3b6de90bf998fe96a79813a080a1ff0f730b722a834f6797d1a68a57595e477489371153d75b9d0491af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
